CREATE (:Concept {id: 'cuda', name: 'CUDA', definition: 'NVIDIA CUDA parallel computing platform and API', metadata: '{}'});
CREATE (:Concept {id: 'gpu', name: 'GPU', definition: 'Graphics Processing Unit for parallel computation', metadata: '{}'});
CREATE (:Concept {id: 'memory', name: 'Memory Management', definition: 'Memory allocation and management in system programming', metadata: '{}'});
CREATE (:Concept {id: 'compilation', name: 'Compilation', definition: 'Process of converting source code to executable', metadata: '{}'});
CREATE (:Concept {id: 'multi_gpu', name: 'Multi-GPU', definition: 'Using multiple GPUs for parallel training', metadata: '{}'});
CREATE (:Concept {id: 'windows', name: 'Windows', definition: 'Windows operating system compatibility', metadata: '{}'});
CREATE (:Concept {id: 'loss_computation', name: 'Loss Computation', definition: 'Calculation of loss function in neural networks', metadata: '{}'});
CREATE (:Concept {id: 'cudnn', name: 'cuDNN', definition: 'NVIDIA CUDA Deep Neural Network library', metadata: '{}'});
CREATE (:Concept {id: 'training', name: 'Training', definition: 'Model training process', metadata: '{}'});
CREATE (:Concept {id: 'backpropagation', name: 'Backpropagation', definition: 'Gradient computation through backward pass', metadata: '{}'});
CREATE (:Concept {id: 'kernel', name: 'CUDA Kernel', definition: 'Function executed on GPU', metadata: '{}'});
CREATE (:Concept {id: 'mpi', name: 'MPI', definition: 'Message Passing Interface for distributed computing', metadata: '{}'});
CREATE (:Concept {id: 'openmp', name: 'OpenMP', definition: 'API for multi-platform shared-memory parallel programming', metadata: '{}'});
CREATE (:Concept {id: 'layernorm', name: 'Layer Normalization', definition: 'Normalization technique in neural networks', metadata: '{}'});
CREATE (:Concept {id: 'attention', name: 'Attention Mechanism', definition: 'Attention mechanism in transformer models', metadata: '{}'});
CREATE (:Concept {id: 'gpt2', name: 'GPT-2', definition: 'Generative Pre-trained Transformer 2 model', metadata: '{}'});
CREATE (:Concept {id: 'tokenization', name: 'Tokenization', definition: 'Process of converting text to tokens', metadata: '{}'});
CREATE (:Concept {id: 'dataset', name: 'Dataset', definition: 'Training or evaluation data', metadata: '{}'});
CREATE (:Concept {id: 'ci_cd', name: 'CI/CD', definition: 'Continuous Integration and Deployment', metadata: '{}'});
CREATE (:Concept {id: 'macos', name: 'macOS', definition: 'Apple macOS operating system', metadata: '{}'});
CREATE (:Concept {id: 'wsl', name: 'WSL', definition: 'Windows Subsystem for Linux', metadata: '{}'});

CREATE (:Problem {id: 'issue_805', text: 'cuda12.6 link issue with compilation errors', type: 'compilation', variables: 'cuda_version:12.6,compiler:gcc', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/805"}'});
CREATE (:Problem {id: 'issue_799', text: 'Loss computation is wrong - incorrect pairing of logits and labels', type: 'algorithm', variables: 'loss_function', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/799"}'});
CREATE (:Problem {id: 'issue_562', text: 'LLM.c in google colab setup', type: 'setup', variables: 'platform:colab', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/562"}'});
CREATE (:Problem {id: 'issue_798', text: 'How to support deepseek r1', type: 'feature_request', variables: 'model:deepseek_r1', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/798"}'});
CREATE (:Problem {id: 'issue_796', text: 'Wrong MFU with blackwell GPUs', type: 'performance', variables: 'gpu:rtx_5080', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/796"}'});
CREATE (:Problem {id: 'issue_795', text: 'Miscalculating of head index and series index in attention kernel', type: 'bug', variables: 'kernel:attention_softmax', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/795"}'});
CREATE (:Problem {id: 'issue_785', text: 'GitHub access restricted error in hellaswag.py', type: 'external_dependency', variables: 'service:github', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/785"}'});
CREATE (:Problem {id: 'issue_777', text: 'How to make customized dataset', type: 'documentation', variables: 'dataset:custom', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/777"}'});
CREATE (:Problem {id: 'issue_768', text: 'Problem debugging cuda kernel functions', type: 'debugging', variables: 'tool:vscode', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/768"}'});
CREATE (:Problem {id: 'issue_749', text: 'Error no instance of overloaded function matches argument list', type: 'compilation', variables: 'compiler:nvcc', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/749"}'});
CREATE (:Problem {id: 'issue_492', text: 'Cudnn error cudnn_att.cpp on train_gptcu', type: 'runtime', variables: 'library:cudnn,gpu:rtx_4090', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/492"}'});
CREATE (:Problem {id: 'issue_642', text: 'Windows issue with Cuda Toolkit 12.5 and MSVC compiler 17.10', type: 'compatibility', variables: 'os:windows,cuda:12.5,compiler:msvc_17.10', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/642"}'});
CREATE (:Problem {id: 'issue_692', text: 'Multi-GPU config enabled when using one GPU', type: 'configuration', variables: 'gpu_count:1', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/692"}'});
CREATE (:Problem {id: 'issue_622', text: 'sel4 + llm.c for mission critical systems', type: 'feature_request', variables: 'platform:sel4', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/622"}'});
CREATE (:Problem {id: 'issue_566', text: 'OSError: Memory mapping file failed', type: 'runtime', variables: 'platform:hpc,memory:384gb', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/566"}'});
CREATE (:Problem {id: 'issue_312', text: 'void tokenizer_init failed assertion', type: 'runtime', variables: 'component:tokenizer', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/312"}'});
CREATE (:Problem {id: 'issue_563', text: 'Running quick start on CPU on Macbook Pro M2', type: 'setup', variables: 'platform:macos,cpu:m2', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/563"}'});
CREATE (:Problem {id: 'issue_555', text: 'Compatibility issues with earlier c++ versions', type: 'compatibility', variables: 'cpp_version:pre17', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/555"}'});
CREATE (:Problem {id: 'issue_557', text: 'Cannot understand cublasGemmStridedBatchedEx call in attention_forward', type: 'documentation', variables: 'function:cublas_gemm', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/557"}'});
CREATE (:Problem {id: 'issue_527', text: 'ERROR on AMD GPU', type: 'compatibility', variables: 'gpu:amd_7900xtx,platform:rocm', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/527"}'});
CREATE (:Problem {id: 'issue_428', text: 'Mismatch of dweight at layernorm_backward.cu', type: 'bug', variables: 'kernel:layernorm_backward,precision:bfloat', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/428"}'});
CREATE (:Problem {id: 'issue_484', text: 'fineweb.py requires datasets python module', type: 'dependency', variables: 'module:datasets', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/484"}'});
CREATE (:Problem {id: 'issue_229', text: 'Windows Github actions / workflow successfully building', type: 'ci_cd', variables: 'platform:windows,tool:github_actions', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/229"}'});
CREATE (:Problem {id: 'issue_246', text: 'WikiText 103 evaluation', type: 'feature_request', variables: 'dataset:wikitext103', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/246"}'});
CREATE (:Problem {id: 'issue_369', text: 'MultiGPU training hangs', type: 'bug', variables: 'feature:multi_gpu,component:cudastreams', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/369"}'});
CREATE (:Problem {id: 'issue_379', text: 'Llm on small models', type: 'feature_request', variables: 'model_size:small', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/379"}'});
CREATE (:Problem {id: 'issue_368', text: 'make: Error 2 on Windows', type: 'compilation', variables: 'os:windows,compiler:cl', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/368"}'});
CREATE (:Problem {id: 'issue_356', text: 'About pull request of custom kernel implementation', type: 'contribution', variables: 'component:kernel,type:optimization', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/356"}'});
CREATE (:Problem {id: 'issue_202', text: 'gitignore does not ignore all binary files', type: 'repository', variables: 'file:.gitignore', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/202"}'});
CREATE (:Problem {id: 'issue_242', text: 'CI Mac issue with resources for Python', type: 'ci_cd', variables: 'platform:mac,tool:github_actions', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/242"}'});
CREATE (:Problem {id: 'issue_308', text: 'Possible NULL Pointer Dereference', type: 'bug', variables: 'type:memory_safety', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/308"}'});
CREATE (:Problem {id: 'issue_212', text: 'bug: something goes wrong at larger batch sizes', type: 'bug', variables: 'parameter:batch_size', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/212"}'});
CREATE (:Problem {id: 'issue_19', text: 'Error: must forward with targets before backward', type: 'runtime', variables: 'phase:training', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/19"}'});
CREATE (:Problem {id: 'issue_245', text: 'Refactoring all shared cuda helper methods', type: 'code_quality', variables: 'component:cuda_helpers', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/245"}'});
CREATE (:Problem {id: 'issue_144', text: 'Accumulate in double instead of float', type: 'precision', variables: 'datatype:float,datatype:double', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/144"}'});
CREATE (:Problem {id: 'issue_154', text: 'from-scratch init the model', type: 'feature_request', variables: 'initialization:random', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/154"}'});
CREATE (:Problem {id: 'issue_127', text: 'WSL setup details', type: 'setup', variables: 'platform:wsl', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/127"}'});
CREATE (:Problem {id: 'issue_217', text: 'CI tests dependent on connectivity/uptime of huggingface', type: 'ci_cd', variables: 'dependency:huggingface', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/217"}'});
CREATE (:Problem {id: 'issue_206', text: 'Suddenly Out of memory on train/python', type: 'runtime', variables: 'gpu:4090,error:oom', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/206"}'});
CREATE (:Problem {id: 'issue_135', text: 'train_gpt2.cu have not backward?', type: 'documentation', variables: 'component:backprop', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/135"}'});
CREATE (:Problem {id: 'issue_178', text: '__stcs in layernorm_forward_kernel3 function', type: 'bug', variables: 'function:stcs,precision:half', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/178"}'});
CREATE (:Problem {id: 'issue_74', text: 'OMP: Error 15: Initializing libomp.dylib', type: 'runtime', variables: 'library:openmp,platform:mac', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/74"}'});
CREATE (:Problem {id: 'issue_147', text: 'use const properly in function signatures', type: 'code_quality', variables: 'keyword:const', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/147"}'});
CREATE (:Problem {id: 'issue_157', text: 'Understand codebase with custom GPT', type: 'documentation', variables: 'tool:gpt', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/157"}'});
CREATE (:Problem {id: 'issue_148', text: 'Qlora on CPU Error with Qwen-14B-Chat', type: 'runtime', variables: 'model:qwen14b,method:qlora', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/148"}'});
CREATE (:Problem {id: 'issue_94', text: 'Suggested to add check for return value of Malloc', type: 'code_quality', variables: 'function:malloc', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/94"}'});
CREATE (:Problem {id: 'issue_85', text: 'no CUDA-capable device is detected', type: 'setup', variables: 'platform:wsl2,cuda:11.5', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/85"}'});
CREATE (:Problem {id: 'issue_114', text: 'CUDA ERROR illegal memory access', type: 'runtime', variables: 'error:illegal_memory_access', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/114"}'});
CREATE (:Problem {id: 'issue_103', text: 'Infini-attention implementation', type: 'feature_request', variables: 'feature:infini_attention', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/103"}'});
CREATE (:Problem {id: 'issue_54', text: 'Fused bias with matmul using cublasLtMatmul', type: 'optimization', variables: 'function:cublasLtMatmul', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/54"}'});
CREATE (:Problem {id: 'issue_83', text: 'Suggestion: Discussions tab for general help', type: 'repository', variables: 'feature:discussions', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/83"}'});
CREATE (:Problem {id: 'issue_86', text: 'What else can I say, awesome', type: 'feedback', variables: 'type:positive', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/86"}'});
CREATE (:Problem {id: 'issue_91', text: 'AI is Artificial Idiot', type: 'feedback', variables: 'type:negative', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/91"}'});
CREATE (:Problem {id: 'issue_96', text: 'Does it have interactive mode like ChatGPT', type: 'feature_request', variables: 'feature:interactive_mode', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/96"}'});
CREATE (:Problem {id: 'issue_57', text: 'Precompute scaling factor in gelu_forward and gelu_backward', type: 'optimization', variables: 'function:gelu', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/57"}'});
CREATE (:Problem {id: 'issue_81', text: 'RuntimeError: must forward with targets before backward', type: 'runtime', variables: 'phase:training', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/81"}'});
CREATE (:Problem {id: 'issue_52', text: 'Clarify param_sizes calculation', type: 'documentation', variables: 'function:gpt2_build_from_checkpoint', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/52"}'});
CREATE (:Problem {id: 'issue_73', text: 'AssertionError: Torch not compiled with CUDA enabled', type: 'setup', variables: 'library:pytorch', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/73"}'});
CREATE (:Problem {id: 'issue_17', text: 'error running makefile train_gpt2 on windows', type: 'compilation', variables: 'os:windows', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/17"}'});
CREATE (:Problem {id: 'issue_30', text: 'python train_gpt2.py errors after 10 iterations', type: 'runtime', variables: 'platform:mac', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/30"}'});
CREATE (:Problem {id: 'issue_13', text: 'Port special architecture into project', type: 'feature_request', variables: 'architecture:llama2rnn', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/13"}'});
CREATE (:Problem {id: 'issue_41', text: 'project license', type: 'repository', variables: 'file:license', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/41"}'});
CREATE (:Problem {id: 'issue_43', text: 'Add .gitignore to project', type: 'repository', variables: 'file:.gitignore', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/43"}'});
CREATE (:Problem {id: 'issue_29', text: 'Waiting for CUDA implement', type: 'feature_request', variables: 'implementation:cuda', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/29"}'});
CREATE (:Problem {id: 'issue_8', text: 'OverflowError: cant convert negative int to unsigned', type: 'runtime', variables: 'platform:mac', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/8"}'});
CREATE (:Problem {id: 'issue_32', text: 'Error: backward before forward', type: 'runtime', variables: 'phase:training', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/32"}'});
CREATE (:Problem {id: 'issue_22', text: 'Will it be a walkthrough tutorial', type: 'documentation', variables: 'type:tutorial', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/22"}'});
CREATE (:Problem {id: 'issue_7', text: 'Dead stores', type: 'code_quality', variables: 'analysis:static', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/7"}'});
CREATE (:Problem {id: 'issue_6', text: 'Not all heroes wear capes', type: 'feedback', variables: 'type:appreciation', metadata: '{"url":"https://github.com/karpathy/llm.c/issues/6"}'});

CREATE (:Solution {id: 'pr_703', problem_id: 'issue_642', expression: 'Move WIN32 code from utils.h to unistd.h', verified: true, metadata: '{"pr_url":"https://github.com/karpathy/llm.c/pull/703"}'});
CREATE (:Solution {id: 'pr_476', problem_id: 'issue_428', expression: 'Accumulate in float32 temp array before writing as bfloat16', verified: true, metadata: '{"pr_url":"https://github.com/karpathy/llm.c/pull/476"}'});
CREATE (:Solution {id: 'pr_382', problem_id: 'issue_369', expression: 'Fix for MultiGPU training hang issue', verified: true, metadata: '{"pr_url":"https://github.com/karpathy/llm.c/pull/382"}'});
CREATE (:Solution {id: 'pr_239', problem_id: 'issue_202', expression: 'Add binary files to .gitignore with minimal msvc ignores', verified: true, metadata: '{"pr_url":"https://github.com/karpathy/llm.c/pull/239"}'});
CREATE (:Solution {id: 'pr_221', problem_id: 'issue_144', expression: 'Accumulate in double precision for better accuracy', verified: true, metadata: '{"pr_url":"https://github.com/karpathy/llm.c/pull/221"}'});
CREATE (:Solution {id: 'pr_164', problem_id: 'issue_147', expression: 'Refactor function declarations to use const properly', verified: true, metadata: '{"pr_url":"https://github.com/karpathy/llm.c/pull/164"}'});

CREATE (:Method {id: 'precision_upgrade', name: 'Precision Upgrade', preconditions: 'Accumulation operations with precision loss', metadata: '{}'});
CREATE (:Method {id: 'code_refactoring', name: 'Code Refactoring', preconditions: 'Code quality issues', metadata: '{}'});
CREATE (:Method {id: 'dependency_fix', name: 'Dependency Fix', preconditions: 'Missing or incompatible dependencies', metadata: '{}'});
CREATE (:Method {id: 'platform_adaptation', name: 'Platform Adaptation', preconditions: 'Platform-specific issues', metadata: '{}'});
CREATE (:Method {id: 'synchronization_fix', name: 'Synchronization Fix', preconditions: 'Multi-threaded or multi-GPU sync issues', metadata: '{}'});
CREATE (:Method {id: 'downgrade_version', name: 'Version Downgrade', preconditions: 'Compatibility issues with new versions', metadata: '{}'});
CREATE (:Method {id: 'manual_patch', name: 'Manual Patch', preconditions: 'Known code issues without official fix', metadata: '{}'});
CREATE (:Method {id: 'environment_setup', name: 'Environment Setup', preconditions: 'Platform-specific configuration needed', metadata: '{}'});

MATCH (s:Solution {id: 'pr_703'}), (p:Problem {id: 'issue_642'}) CREATE (s)-[:SOLVES {created_at: timestamp()}]->(p);
MATCH (s:Solution {id: 'pr_476'}), (p:Problem {id: 'issue_428'}) CREATE (s)-[:SOLVES {created_at: timestamp()}]->(p);
MATCH (s:Solution {id: 'pr_382'}), (p:Problem {id: 'issue_369'}) CREATE (s)-[:SOLVES {created_at: timestamp()}]->(p);
MATCH (s:Solution {id: 'pr_239'}), (p:Problem {id: 'issue_202'}) CREATE (s)-[:SOLVES {created_at: timestamp()}]->(p);
MATCH (s:Solution {id: 'pr_221'}), (p:Problem {id: 'issue_144'}) CREATE (s)-[:SOLVES {created_at: timestamp()}]->(p);
MATCH (s:Solution {id: 'pr_164'}), (p:Problem {id: 'issue_147'}) CREATE (s)-[:SOLVES {created_at: timestamp()}]->(p);

MATCH (p:Problem {id: 'issue_805'}), (c:Concept {id: 'cuda'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_805'}), (c:Concept {id: 'compilation'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_799'}), (c:Concept {id: 'loss_computation'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_799'}), (c:Concept {id: 'training'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_795'}), (c:Concept {id: 'attention'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_795'}), (c:Concept {id: 'kernel'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_492'}), (c:Concept {id: 'cudnn'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_642'}), (c:Concept {id: 'windows'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_642'}), (c:Concept {id: 'cuda'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_692'}), (c:Concept {id: 'multi_gpu'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_692'}), (c:Concept {id: 'mpi'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_566'}), (c:Concept {id: 'memory'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_312'}), (c:Concept {id: 'tokenization'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_563'}), (c:Concept {id: 'macos'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_527'}), (c:Concept {id: 'gpu'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_428'}), (c:Concept {id: 'layernorm'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_428'}), (c:Concept {id: 'backpropagation'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_369'}), (c:Concept {id: 'multi_gpu'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_368'}), (c:Concept {id: 'windows'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_368'}), (c:Concept {id: 'compilation'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_144'}), (c:Concept {id: 'kernel'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_785'}), (c:Concept {id: 'dataset'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_777'}), (c:Concept {id: 'dataset'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_768'}), (c:Concept {id: 'kernel'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_768'}), (c:Concept {id: 'cuda'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_749'}), (c:Concept {id: 'compilation'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_749'}), (c:Concept {id: 'cuda'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_555'}), (c:Concept {id: 'compilation'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_557'}), (c:Concept {id: 'attention'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_484'}), (c:Concept {id: 'dataset'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_796'}), (c:Concept {id: 'gpu'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_798'}), (c:Concept {id: 'gpt2'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_562'}), (c:Concept {id: 'gpu'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_562'}), (c:Concept {id: 'training'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_127'}), (c:Concept {id: 'wsl'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_127'}), (c:Concept {id: 'cuda'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_85'}), (c:Concept {id: 'wsl'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_85'}), (c:Concept {id: 'cuda'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_74'}), (c:Concept {id: 'openmp'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_74'}), (c:Concept {id: 'macos'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_178'}), (c:Concept {id: 'layernorm'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_178'}), (c:Concept {id: 'kernel'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_135'}), (c:Concept {id: 'backpropagation'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_135'}), (c:Concept {id: 'training'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_19'}), (c:Concept {id: 'training'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_19'}), (c:Concept {id: 'backpropagation'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_81'}), (c:Concept {id: 'training'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_32'}), (c:Concept {id: 'training'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_17'}), (c:Concept {id: 'windows'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_17'}), (c:Concept {id: 'compilation'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_229'}), (c:Concept {id: 'ci_cd'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_229'}), (c:Concept {id: 'windows'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_242'}), (c:Concept {id: 'ci_cd'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_242'}), (c:Concept {id: 'macos'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_217'}), (c:Concept {id: 'ci_cd'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_308'}), (c:Concept {id: 'memory'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_94'}), (c:Concept {id: 'memory'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_206'}), (c:Concept {id: 'memory'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_206'}), (c:Concept {id: 'gpu'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_114'}), (c:Concept {id: 'memory'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_114'}), (c:Concept {id: 'cuda'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_212'}), (c:Concept {id: 'memory'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_212'}), (c:Concept {id: 'training'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_245'}), (c:Concept {id: 'cuda'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_245'}), (c:Concept {id: 'kernel'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_356'}), (c:Concept {id: 'kernel'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_57'}), (c:Concept {id: 'kernel'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_54'}), (c:Concept {id: 'cuda'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_103'}), (c:Concept {id: 'attention'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_154'}), (c:Concept {id: 'gpt2'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_154'}), (c:Concept {id: 'training'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_246'}), (c:Concept {id: 'dataset'}) CREATE (p)-[:ABOUT]->(c);
MATCH (p:Problem {id: 'issue_246'}), (c:Concept {id: 'gpt2'}) CREATE (p)-[:ABOUT]->(c);

MATCH (m:Method {id: 'precision_upgrade'}), (p:Problem {id: 'issue_428'}) CREATE (m)-[:APPLIES_TO]->(p);
MATCH (m:Method {id: 'precision_upgrade'}), (p:Problem {id: 'issue_144'}) CREATE (m)-[:APPLIES_TO]->(p);
MATCH (m:Method {id: 'code_refactoring'}), (p:Problem {id: 'issue_147'}) CREATE (m)-[:APPLIES_TO]->(p);
MATCH (m:Method {id: 'code_refactoring'}), (p:Problem {id: 'issue_202'}) CREATE (m)-[:APPLIES_TO]->(p);
MATCH (m:Method {id: 'platform_adaptation'}), (p:Problem {id: 'issue_642'}) CREATE (m)-[:APPLIES_TO]->(p);
MATCH (m:Method {id: 'platform_adaptation'}), (p:Problem {id: 'issue_368'}) CREATE (m)-[:APPLIES_TO]->(p);
MATCH (m:Method {id: 'synchronization_fix'}), (p:Problem {id: 'issue_369'}) CREATE (m)-[:APPLIES_TO]->(p);
MATCH (m:Method {id: 'dependency_fix'}), (p:Problem {id: 'issue_484'}) CREATE (m)-[:APPLIES_TO]->(p);

MATCH (m:Method {id: 'precision_upgrade'}), (c:Concept {id: 'kernel'}) CREATE (m)-[:USES]->(c);
MATCH (m:Method {id: 'synchronization_fix'}), (c:Concept {id: 'multi_gpu'}) CREATE (m)-[:USES]->(c);
MATCH (m:Method {id: 'platform_adaptation'}), (c:Concept {id: 'windows'}) CREATE (m)-[:USES]->(c);
MATCH (m:Method {id: 'platform_adaptation'}), (c:Concept {id: 'cuda'}) CREATE (m)-[:USES]->(c);

MATCH (s:Solution {id: 'pr_703'}), (c:Concept {id: 'windows'}) CREATE (s)-[:REFERENCES]->(c);
MATCH (s:Solution {id: 'pr_476'}), (c:Concept {id: 'layernorm'}) CREATE (s)-[:REFERENCES]->(c);
MATCH (s:Solution {id: 'pr_382'}), (c:Concept {id: 'multi_gpu'}) CREATE (s)-[:REFERENCES]->(c);
MATCH (s:Solution {id: 'pr_221'}), (c:Concept {id: 'kernel'}) CREATE (s)-[:REFERENCES]->(c);
MATCH (s:Solution {id: 'pr_164'}), (c:Concept {id: 'compilation'}) CREATE (s)-[:REFERENCES]->(c);



MATCH (m:Model {id: 'gpt2'}), (p:Problem {id: 'issue_799'}) CREATE (m)-[:CAN_SOLVE {confidence: 0.7}]->(p);
MATCH (m:Model {id: 'gpt2'}), (p:Problem {id: 'issue_154'}) CREATE (m)-[:CAN_SOLVE {confidence: 0.9}]->(p);
MATCH (m:Model {id: 'gpt2'}), (p:Problem {id: 'issue_246'}) CREATE (m)-[:CAN_SOLVE {confidence: 0.8}]->(p);
MATCH (m:Model {id: 'gpt2_124m'}), (p:Problem {id: 'issue_799'}) CREATE (m)-[:CAN_SOLVE {confidence: 0.6}]->(p);
MATCH (m:Model {id: 'gpt2_124m'}), (p:Problem {id: 'issue_212'}) CREATE (m)-[:CANT_SOLVE {reason: 'memory_limitations'}]->(p);
MATCH (m:Model {id: 'gpt2_124m'}), (p:Problem {id: 'issue_206'}) CREATE (m)-[:CANT_SOLVE {reason: 'oom_error'}]->(p);
MATCH (m:Model {id: 'qwen_14b'}), (p:Problem {id: 'issue_148'}) CREATE (m)-[:CANT_SOLVE {reason: 'cpu_quantization_unsupported'}]->(p);
MATCH (m:Model {id: 'deepseek_r1'}), (p:Problem {id: 'issue_798'}) CREATE (m)-[:CAN_SOLVE {confidence: 0.5}]->(p);
MATCH (m:Model {id: 'llama2'}), (p:Problem {id: 'issue_13'}) CREATE (m)-[:CAN_SOLVE {confidence: 0.4}]->(p);
MATCH (m:Model {id: 'claude_opus'}), (p:Problem {id: 'issue_157'}) CREATE (m)-[:CAN_SOLVE {confidence: 0.95}]->(p);
MATCH (m:Model {id: 'claude_opus'}), (p:Problem {id: 'issue_245'}) CREATE (m)-[:CAN_SOLVE {confidence: 0.9}]->(p);
MATCH (m:Model {id: 'claude_opus'}), (p:Problem {id: 'issue_356'}) CREATE (m)-[:CAN_SOLVE {confidence: 0.85}]->(p);
MATCH (m:Model {id: 'gpt4'}), (p:Problem {id: 'issue_103'}) CREATE (m)-[:CAN_SOLVE {confidence: 0.8}]->(p);
MATCH (m:Model {id: 'gpt4'}), (p:Problem {id: 'issue_157'}) CREATE (m)-[:CAN_SOLVE {confidence: 0.9}]->(p);
MATCH (m:Model {id: 'gpt2'}), (p:Problem {id: 'issue_555'}) CREATE (m)-[:CANT_SOLVE {reason: 'requires_cpp17_features'}]->(p);
MATCH (m:Model {id: 'gpt2'}), (p:Problem {id: 'issue_642'}) CREATE (m)-[:CANT_SOLVE {reason: 'platform_specific_issue'}]->(p);
MATCH (m:Model {id: 'gpt2_124m'}), (p:Problem {id: 'issue_369'}) CREATE (m)-[:CANT_SOLVE {reason: 'multi_gpu_not_supported'}]->(p);
MATCH (m:Model {id: 'llama2'}), (p:Problem {id: 'issue_492'}) CREATE (m)-[:CANT_SOLVE {reason: 'cudnn_incompatibility'}]->(p);

MATCH (p1:Problem {id: 'issue_805'}), (p2:Problem {id: 'issue_749'}) CREATE (p1)-[:RELATED_TO {similarity: 0.8}]->(p2);
MATCH (p1:Problem {id: 'issue_805'}), (p2:Problem {id: 'issue_368'}) CREATE (p1)-[:RELATED_TO {similarity: 0.7}]->(p2);
MATCH (p1:Problem {id: 'issue_555'}), (p2:Problem {id: 'issue_749'}) CREATE (p1)-[:RELATED_TO {similarity: 0.6}]->(p2);
MATCH (p1:Problem {id: 'issue_796'}), (p2:Problem {id: 'issue_527'}) CREATE (p1)-[:RELATED_TO {similarity: 0.7}]->(p2);
MATCH (p1:Problem {id: 'issue_492'}), (p2:Problem {id: 'issue_369'}) CREATE (p1)-[:RELATED_TO {similarity: 0.6}]->(p2);
MATCH (p1:Problem {id: 'issue_566'}), (p2:Problem {id: 'issue_312'}) CREATE (p1)-[:RELATED_TO {similarity: 0.5}]->(p2);
MATCH (p1:Problem {id: 'issue_642'}), (p2:Problem {id: 'issue_368'}) CREATE (p1)-[:RELATED_TO {similarity: 0.9}]->(p2);
MATCH (p1:Problem {id: 'issue_777'}), (p2:Problem {id: 'issue_785'}) CREATE (p1)-[:RELATED_TO {similarity: 0.7}]->(p2);
MATCH (p1:Problem {id: 'issue_777'}), (p2:Problem {id: 'issue_484'}) CREATE (p1)-[:RELATED_TO {similarity: 0.6}]->(p2);
MATCH (p1:Problem {id: 'issue_127'}), (p2:Problem {id: 'issue_85'}) CREATE (p1)-[:RELATED_TO {similarity: 0.9}]->(p2);
MATCH (p1:Problem {id: 'issue_19'}), (p2:Problem {id: 'issue_81'}) CREATE (p1)-[:RELATED_TO {similarity: 0.9}]->(p2);
MATCH (p1:Problem {id: 'issue_19'}), (p2:Problem {id: 'issue_32'}) CREATE (p1)-[:RELATED_TO {similarity: 0.9}]->(p2);
MATCH (p1:Problem {id: 'issue_81'}), (p2:Problem {id: 'issue_32'}) CREATE (p1)-[:RELATED_TO {similarity: 0.8}]->(p2);
MATCH (p1:Problem {id: 'issue_308'}), (p2:Problem {id: 'issue_94'}) CREATE (p1)-[:RELATED_TO {similarity: 0.7}]->(p2);
MATCH (p1:Problem {id: 'issue_206'}), (p2:Problem {id: 'issue_114'}) CREATE (p1)-[:RELATED_TO {similarity: 0.6}]->(p2);
MATCH (p1:Problem {id: 'issue_206'}), (p2:Problem {id: 'issue_212'}) CREATE (p1)-[:RELATED_TO {similarity: 0.7}]->(p2);
MATCH (p1:Problem {id: 'issue_202'}), (p2:Problem {id: 'issue_43'}) CREATE (p1)-[:RELATED_TO {similarity: 0.9}]->(p2);
MATCH (p1:Problem {id: 'issue_229'}), (p2:Problem {id: 'issue_242'}) CREATE (p1)-[:RELATED_TO {similarity: 0.6}]->(p2);
MATCH (p1:Problem {id: 'issue_229'}), (p2:Problem {id: 'issue_217'}) CREATE (p1)-[:RELATED_TO {similarity: 0.6}]->(p2);
MATCH (p1:Problem {id: 'issue_242'}), (p2:Problem {id: 'issue_217'}) CREATE (p1)-[:RELATED_TO {similarity: 0.7}]->(p2);
MATCH (p1:Problem {id: 'issue_17'}), (p2:Problem {id: 'issue_368'}) CREATE (p1)-[:RELATED_TO {similarity: 0.8}]->(p2);
MATCH (p1:Problem {id: 'issue_428'}), (p2:Problem {id: 'issue_178'}) CREATE (p1)-[:RELATED_TO {similarity: 0.7}]->(p2);
MATCH (p1:Problem {id: 'issue_8'}), (p2:Problem {id: 'issue_30'}) CREATE (p1)-[:RELATED_TO {similarity: 0.7}]->(p2);
MATCH (p1:Problem {id: 'issue_245'}), (p2:Problem {id: 'issue_356'}) CREATE (p1)-[:RELATED_TO {similarity: 0.6}]->(p2);
MATCH (p1:Problem {id: 'issue_57'}), (p2:Problem {id: 'issue_54'}) CREATE (p1)-[:RELATED_TO {similarity: 0.5}]->(p2);
MATCH (p1:Problem {id: 'issue_795'}), (p2:Problem {id: 'issue_557'}) CREATE (p1)-[:RELATED_TO {similarity: 0.7}]->(p2);
MATCH (p1:Problem {id: 'issue_103'}), (p2:Problem {id: 'issue_557'}) CREATE (p1)-[:RELATED_TO {similarity: 0.5}]->(p2);

MATCH (c1:Concept {id: 'cuda'}), (c2:Concept {id: 'gpu'}) CREATE (c1)-[:DEPENDS_ON]->(c2);
MATCH (c1:Concept {id: 'cudnn'}), (c2:Concept {id: 'cuda'}) CREATE (c1)-[:DEPENDS_ON]->(c2);
MATCH (c1:Concept {id: 'multi_gpu'}), (c2:Concept {id: 'gpu'}) CREATE (c1)-[:DEPENDS_ON]->(c2);
MATCH (c1:Concept {id: 'multi_gpu'}), (c2:Concept {id: 'mpi'}) CREATE (c1)-[:DEPENDS_ON]->(c2);
MATCH (c1:Concept {id: 'kernel'}), (c2:Concept {id: 'cuda'}) CREATE (c1)-[:DEPENDS_ON]->(c2);
MATCH (c1:Concept {id: 'attention'}), (c2:Concept {id: 'kernel'}) CREATE (c1)-[:DEPENDS_ON]->(c2);
MATCH (c1:Concept {id: 'layernorm'}), (c2:Concept {id: 'kernel'}) CREATE (c1)-[:DEPENDS_ON]->(c2);
MATCH (c1:Concept {id: 'gpt2'}), (c2:Concept {id: 'attention'}) CREATE (c1)-[:DEPENDS_ON]->(c2);
MATCH (c1:Concept {id: 'gpt2'}), (c2:Concept {id: 'training'}) CREATE (c1)-[:DEPENDS_ON]->(c2);
MATCH (c1:Concept {id: 'training'}), (c2:Concept {id: 'backpropagation'}) CREATE (c1)-[:DEPENDS_ON]->(c2);
MATCH (c1:Concept {id: 'training'}), (c2:Concept {id: 'loss_computation'}) CREATE (c1)-[:DEPENDS_ON]->(c2);
MATCH (c1:Concept {id: 'backpropagation'}), (c2:Concept {id: 'memory'}) CREATE (c1)-[:DEPENDS_ON]->(c2);
MATCH (c1:Concept {id: 'wsl'}), (c2:Concept {id: 'windows'}) CREATE (c1)-[:DEPENDS_ON]->(c2);

MATCH (p1:Problem {id: 'issue_555'}), (p2:Problem {id: 'issue_749'}) CREATE (p1)-[:CAUSED_BY]->(p2);
MATCH (p1:Problem {id: 'issue_369'}), (p2:Problem {id: 'issue_692'}) CREATE (p1)-[:CAUSED_BY]->(p2);

MATCH (m:Method {id: 'downgrade_version'}), (p:Problem {id: 'issue_642'}) CREATE (m)-[:WORKAROUND_FOR]->(p);
MATCH (m:Method {id: 'downgrade_version'}), (p:Problem {id: 'issue_555'}) CREATE (m)-[:WORKAROUND_FOR]->(p);
MATCH (m:Method {id: 'manual_patch'}), (p:Problem {id: 'issue_799'}) CREATE (m)-[:WORKAROUND_FOR]->(p);
MATCH (m:Method {id: 'manual_patch'}), (p:Problem {id: 'issue_795'}) CREATE (m)-[:WORKAROUND_FOR]->(p);
MATCH (m:Method {id: 'environment_setup'}), (p:Problem {id: 'issue_563'}) CREATE (m)-[:WORKAROUND_FOR]->(p);
MATCH (m:Method {id: 'environment_setup'}), (p:Problem {id: 'issue_527'}) CREATE (m)-[:WORKAROUND_FOR]->(p);

MATCH (s1:Solution {id: 'pr_476'}), (s2:Solution {id: 'pr_221'}) CREATE (s1)-[:SIMILAR_TO {similarity: 0.8}]->(s2);
MATCH (s1:Solution {id: 'pr_164'}), (s2:Solution {id: 'pr_239'}) CREATE (s1)-[:SIMILAR_TO {similarity: 0.6}]->(s2);
